---
id: osrk04
base_name: scenario
tags:
  - ruby
presentation_date: "2024-08-24"
version: 1.0.0
licenses: ['MIT']
author:
  markup_language: rd
  name: makicamel
  email: unright@gmail.com
  rubygems_user: makicamel
source_code_uri: "https://github.com/makicamel/osrk04"
